### ISSUE TITLE
WPScan Error

### ISSUE THREAD

**Issue by Nitr0X-CL** [olacabs/jackhammer#111]
Hi,

I have a problem when launch wpscan the status is complete in 0 second

log /scans/id.log
root@af46b2f72134:/home/app# tail -f log/scans/19.log 
Error===>#<NoMethodError: undefined method `user_agent=' for Typhoeus::Config:Module>

log /log/sidekip.log
2019-01-08T03:12:51.774Z 71 TID-oty8v4uyg WpScanWorker JID-a74098a0ca765fac1246f935 INFO: start
2019-01-08T03:12:52.046Z 71 TID-oty8v4uyg WpScanWorker JID-a74098a0ca765fac1246f935 INFO: fail: 0.273 sec
2019-01-08T03:12:52.047Z 71 TID-oty8v4uyg WpScanWorker JID-a74098a0ca765fac1246f935 INFO: Adding dead WpScanWorker job a74098a0ca765fac1246f935
2019-01-08T03:12:52.047Z 71 TID-oty8v4uyg WARN: {"context":"Job raised exception","job":{"class":"WpScanWorker","args":[19,36],"retry":2,"queue":"wordpress","backtrace":true,"unique":"while_executing","jid":"a7$
2019-01-08T03:12:52.047Z 71 TID-oty8v4uyg WARN: Errno::ECONNREFUSED: Connection refused - connect(2) for "" port 0
2019-01-08T03:12:52.047Z 71 TID-oty8v4uyg WARN: /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `initialize'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `open'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start'
/root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:260:in `block in deliver'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:260:in `deliver'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:105:in `deliver'
/home/app/app/models/scaner.rb:167:in `send_notifications'
/home/app/app/workers/wp_scan_worker.rb:348:in `perform'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-status-0.7.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:11:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/middleware.rb:10:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-retries-0.4.0/lib/sidekiq/retries/server/middleware.rb:15:in `call'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'

**Comment by kmadhusudhan** [comment]
@Nitr0X-CL 
We are working on **jackhammer version 2** and we released beta version .  jch-v2 branch having beta version changes . please do setup with  jch-v2 branch and try it out
