### ISSUE TITLE
default credencials not working 

### ISSUE THREAD

**Issue by 007scorpio** [olacabs/jackhammer#45]
after installation i tried to log int with 

username: jackhammer@olacabs.com

password: j4ckh4mm3r

yet it gives me invalid email or password

**Comment by kmadhusudhan** [comment]
In Single User mode, there are no  default credentials, you need to do signup

**Comment by JSStone** [comment]
When I try to signup I can't select any team (the drop down list is not populated), and it is mandatory.
Is there way to add team so that I can sign?

**Comment by kmadhusudhan** [comment]
let me know how your doing build

**Comment by 007scorpio** [comment]
default credencials is working now... But Please i can't load android apk. It tells "project content type is invalid" Can u please help?

**Comment by sleepywolf** [comment]
Hello, just installed and the default credentials are not working on mine. Tried to create a register a new login and it requires a team as the initial user wrote. Tried several combinations of the password as well. Any help would be appreciated!

**Comment by sleepywolf** [comment]
Ok, maybe I should've have checked to see if all Docker containers are started! Nevermind - user error!

**Comment by runconnect** [comment]
Hi,

I get the same problem. The script return the error message :

----%<------------------------------
[...]
Starting jackhammer-db ... done
== 20160820175605 CreateFindingsScaners: migrating ============================
-- create_table(:findings_scaners)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_findings_scaners_on_finding_id' on table 'findings_scaners' already exists
/home/app/db/migrate/20160820175605_create_findings_scaners.rb:3:in `change'
ArgumentError: Index name 'index_findings_scaners_on_finding_id' on table 'findings_scaners' already exists
/home/app/db/migrate/20160820175605_create_findings_scaners.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Starting jackhammer_redis_1 ... done
You have 81 pending migrations:
  20160825115945 AddColumnUserIdToComments
  20160826102326 ChangeDefaultVlaueStatus
  20160826102741 AddColumnToFindingsIsFlasePositive
[...]
Run `rake db:migrate` to update your database then try again.
Starting jackhammer-db ... 
Starting jackhammer-db ... done
     _    _     ____  _  __ _   _     _     __  __  __  __  _____  ____    ___  ____    _   _  ____  
    | |  / \   / ___|| |/ /| | | |   / \   |  \/  ||  \/  || ____||  _ \  |_ _|/ ___|  | | | ||  _ \ 
 _  | | / _ \ | |    | ' / | |_| |  / _ \  | |\/| || |\/| ||  _|  | |_) |  | | \___ \  | | | || |_) |
| |_| |/ ___ \| |___ | . \ |  _  | / ___ \ | |  | || |  | || |___ |  _ <   | |  ___) | | |_| ||  __/ 
 \___//_/   \_\\____||_|\_\|_| |_|/_/   \_\|_|  |_||_|  |_||_____||_| \_\ |___||____/   \___/ |_|
----%<------------------------------

How can I fix it ?

Thanks so much.

Best regards,

**Comment by sleepywolf** [comment]
Can you blow out the container, restart Docker, and then retry as SU or SUDO? I had to go back and make sure all of the services were running.

**Comment by juushya** [comment]
## FIX

1. Reboot the box
2. Run docker-build.sh again
3. Start jackhammer services

**Team** option should be accessible now.

HTH.

**Comment by vickybyou** [comment]
Hello,

I am running Jackhammer locally using rails method, but i am not able to login using the default credentials i.e.,
**Username: jackhammer@olacabs.com
password: j4ckh4mm3r**

I have done the DB installation and configured mysql as shown below.I have also taken care of all the gems and dependencies.

**default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  port: 3306
  username: root
  password: pass
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: jackhammer_development
test:
  <<: *default
  database: jackhammer_test
production:
  <<: *default
  database: jackhammer_production**

After doing all the required installation i ran the command 
**bin/rake db:migrate RAILS_ENV=production** 

also 

**bin/rake db:migrate RAILS_ENV=development**

separately but still same issue.

I have created databases in mysql as well.

**mysql> show databases;
+------------------------+
| Database               |
+------------------------+
| information_schema     |
| jackhammer_development |
| jackhammer_production  |
| jackhammer_test        |
| mysql                  |
| performance_schema     |
| sys                    |
+------------------------+
7 rows in set (0,00 sec)**

Then finally i did this,

rails s
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000

Now when i enter the default credentials or try to register i am not able to login, below is the **development.log** result..

**I, [2017-11-03T10:45:16.824262 #5598]  INFO -- : Started POST "/users/sign_in" for 127.0.0.1 at 2017-11-03 10:45:16 +0100
I, [2017-11-03T10:45:16.831569 #5598]  INFO -- : Processing by Devise::SessionsController#create as HTML
I, [2017-11-03T10:45:16.831674 #5598]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"A/7MsxMp6f32zN2sbZKlTSCH23GYoYK+Wci24Lri1/a33EYOVUGYDq14Rkx2cL25iMb/6ff1BJRLKeMycQpe5Q==", "user"=>{"email"=>"jackhammer@olacabs.com", "password"=>"[FILTERED]"}, "commit"=>"LOGIN"}
D, [2017-11-03T10:45:16.835452 #5598] DEBUG -- :   [1m[36mUser Load (0.4ms)[0m  [1mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'jackhammer@olacabs.com'  ORDER BY `users`.`id` ASC LIMIT 1[0m
I, [2017-11-03T10:45:16.835800 #5598]  INFO -- : Completed 401 Unauthorized in 4ms (ActiveRecord: 0.9ms)
I, [2017-11-03T10:45:16.836908 #5598]  INFO -- : Processing by Devise::SessionsController#new as HTML
I, [2017-11-03T10:45:16.837000 #5598]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"A/7MsxMp6f32zN2sbZKlTSCH23GYoYK+Wci24Lri1/a33EYOVUGYDq14Rkx2cL25iMb/6ff1BJRLKeMycQpe5Q==", "user"=>{"email"=>"jackhammer@olacabs.com", "password"=>"[FILTERED]"}, "commit"=>"LOGIN"}
I, [2017-11-03T10:45:16.980094 #5598]  INFO -- :   Rendered users/sessions/new.html.erb within layouts/application (1.5ms)
I, [2017-11-03T10:45:17.477418 #5598]  INFO -- : Completed 200 OK in 640ms (Views: 500.2ms | ActiveRecord: 0.0ms)
D, [2017-11-03T10:45:55.746744 #5598] DEBUG -- : 
D, [2017-11-03T10:45:55.746873 #5598] DEBUG -- : 
I, [2017-11-03T10:45:55.747045 #5598]  INFO -- : Started GET "/users/sign_up" for 127.0.0.1 at 2017-11-03 10:45:55 +0100
I, [2017-11-03T10:45:55.780581 #5598]  INFO -- : Processing by Users::RegistrationsController#new as HTML
D, [2017-11-03T10:45:55.810327 #5598] DEBUG -- :   [1m[36mTeam Load (0.4ms)[0m  [1mSELECT `teams`.* FROM `teams`  ORDER BY `teams`.`name` ASC[0m
I, [2017-11-03T10:45:55.848704 #5598]  INFO -- :   Rendered users/registrations/new.html.erb within layouts/application (55.1ms)
I, [2017-11-03T10:45:56.328669 #5598]  INFO -- : Completed 200 OK in 548ms (Views: 542.3ms | ActiveRecord: 2.4ms)**

I hope @KMadhuSudhan @sleepywolf  @juushya or any one could help me out with this issue.

Thanks in advance.
