### ISSUE TITLE
Adding CPP Checker and Klocwork to Jackhammer

### ISSUE THREAD

**Issue by vickybyou** [olacabs/jackhammer#57]
Hello,

  I would like to add the Klocwork and CPP checker to the Jackhammer and take it to the next level. In order to proceed with this i have few queries !!

1. Does Jackhammer support these tools?
2. If yes, please suggest me how to proceed further.

Thank you

**Comment by kmadhusudhan** [comment]
As of now jackhammer does not  support ,we have documented for adding new tool in user-guide . please follow that to integrate new tools

**Comment by vickybyou** [comment]
Ok i shall try doing that. If the scanner is already installed in the system there is no need to clone it to the tool directory right ?

**Comment by kmadhusudhan** [comment]
yes it is not required

**Comment by vickybyou** [comment]
I have added the cppchecker code to /app/lib/pipeline/tasks 
My CppCheck Code is:
```
require 'pipeline/tasks/base_task'
require 'pipeline/util'
require 'nokogiri'

class Pipeline::CppChecker < Pipeline::BaseTask
  Pipeline::Tasks.add self
  include Pipeline::Util

  def initialize(trigger, tracker)
    super(trigger, tracker)
    @name = 'CppChecker'
    @description = "A tool for static C/C++ code analysis"
    @stage = :code
    @labels << "code" << "ruby" << "rails"
  end

  def run
    Dir.chdir("#{@trigger.path}") do
    runsystem(true, "cppcheck", "--enable=warning,style,performance,portability", "--force", "--inconclusive", "--xml-version=2", "--output-file=", "#{@results_file.path}", ".")
    @results_file = Tempfile.new(['cppcheckresults', '.xml'])
    @result = File.open("#{@results_file.path}"){ |f| Nokogiri::XML(f) }
    end
  end

  def analyze
    begin
    @result.xpath('//results/errors/error').each do |error|
      bug_type = error['id']
      description = error['msg']
      location = "" #mapping location
      line = "" #mapping line no
      link = ""
      file = ""  #mapping file
      code = ""  #mapping code
      cvss_score = ""
      solution = ""
      advisory = ""
      user_input = ""
      sev = error['severity'] #mapping severity
      case sev
        when "error"
          severity = 'critical'
        when "warning"
          severity = 'high'
        when "style"
          severity = 'medium'
        when "performance", "portability"
          severity = 'low'
        else
          severity = 'Unknown'
      end
      source = {:scanner => @name, :file => file, :line => line, :code => code}
      fprint = fingerprint("#{description}#{bug_type}#{severity}")
      report bug_type,description,source,severity,fprint,link,location,user_input, advisory,solution,cvss_score
    end

  rescue Exception => e
    Pipeline.warn e.message
    Pipeline.warn e.backtrace
  end

ensure
  FileUtils.rm @results_file #file gets deleted after parsing is done
end
  def supported?
  supported=runsystem(true, "cppcheck", "-version")
    if supported =~ /command not found/
    Pipeline.notify "Run: sudo apt-get install cppcheck"
      return false
    else
      return true
    end
  end

end
```
Later i restarted the tool. As a admin i have enabled CppChecker and later logged out and registered as a new user, since i wont be able to scan repos being an admin.
Then added the target:
**Project title: cpp
Source : Github
Repo URL : https://github.com/tyranid/ZeroNights2017.git
Branch name : master**

I got the status as failed. The logs are below.

The log report log/scan/ 
**[2017-11-28 09:53:19 +0100] Loading scanner...
[2017-11-28 09:53:19 +0100] Mounting ... https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:19 +0100] Mounting target: https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:19 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::DockerMounter:0x00000007a4c408>
[2017-11-28 09:53:19 +0100] In Docker mounter, target: https://github.com/tyranid/ZeroNights2017.git became: 017.git ... wondering if it matched .docker
[2017-11-28 09:53:19 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::FileSystemMounter:0x00000007a3bb08>
[2017-11-28 09:53:19 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000007a3b108>
[2017-11-28 09:53:19 +0100] Mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000007a3b108>
[2017-11-28 09:53:19 +0100] Making base.
[2017-11-28 09:53:19 +0100] Cleaning directory: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:19 +0100] Removing : /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:19 +0100] Cloning into: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:20 +0100] Mounted https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000007a3b108>
[2017-11-28 09:53:20 +0100] Processing target...https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:20 +0100] Running tasks in stage: wait
[2017-11-28 09:53:20 +0100] Running tasks in stage: mount
[2017-11-28 09:53:20 +0100] Running tasks in stage: file
[2017-11-28 09:53:20 +0100] Running tasks in stage: code
[2017-11-28 09:53:20 +0100] code - CppChecker - #<Set:0x00000007c55c68>
[2017-11-28 09:53:20 +0100] undefined method `path' for nil:NilClass
[2017-11-28 09:53:20 +0100] Running tasks in stage: live
[2017-11-28 09:53:20 +0100] Running tasks in stage: done
[2017-11-28 09:53:20 +0100] Have 0 items pre ZAP filter.
[2017-11-28 09:53:20 +0100] Have 0 items post ZAP filter.
[2017-11-28 09:53:20 +0100] Generating report...[:to_s]
[2017-11-28 09:53:20 +0100] Running base reoprt...
[2017-11-28 09:53:43 +0100] Loading scanner...
[2017-11-28 09:53:43 +0100] Mounting ... https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:43 +0100] Mounting target: https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:43 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::DockerMounter:0x007f8514186488>
[2017-11-28 09:53:43 +0100] In Docker mounter, target: https://github.com/tyranid/ZeroNights2017.git became: 017.git ... wondering if it matched .docker
[2017-11-28 09:53:43 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::FileSystemMounter:0x007f8514186078>
[2017-11-28 09:53:43 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x007f8514185e20>
[2017-11-28 09:53:43 +0100] Mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x007f8514185e20>
[2017-11-28 09:53:43 +0100] Making base.
[2017-11-28 09:53:43 +0100] Cleaning directory: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:43 +0100] Removing : /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:43 +0100] Cloning into: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:53:45 +0100] Mounted https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x007f8514185e20>
[2017-11-28 09:53:45 +0100] Processing target...https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:53:45 +0100] Running tasks in stage: wait
[2017-11-28 09:53:45 +0100] Running tasks in stage: mount
[2017-11-28 09:53:45 +0100] Running tasks in stage: file
[2017-11-28 09:53:45 +0100] Running tasks in stage: code
[2017-11-28 09:53:45 +0100] code - CppChecker - #<Set:0x007f84a80c9430>
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="1.80"/>
    <errors>
    </errors>
</results>
[2017-11-28 09:53:45 +0100] Running tasks in stage: live
[2017-11-28 09:53:45 +0100] Running tasks in stage: done
[2017-11-28 09:53:45 +0100] Have 0 items pre ZAP filter.
[2017-11-28 09:53:45 +0100] Have 0 items post ZAP filter.
[2017-11-28 09:53:45 +0100] Generating report...[:to_s]
[2017-11-28 09:53:45 +0100] Running base reoprt...
[2017-11-28 09:54:46 +0100] Loading scanner...
[2017-11-28 09:54:46 +0100] Mounting ... https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:54:46 +0100] Mounting target: https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:54:46 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::DockerMounter:0x00000008a6f600>
[2017-11-28 09:54:46 +0100] In Docker mounter, target: https://github.com/tyranid/ZeroNights2017.git became: 017.git ... wondering if it matched .docker
[2017-11-28 09:54:46 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::FileSystemMounter:0x00000008a6f1c8>
[2017-11-28 09:54:46 +0100] Checking about mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000008a6ef70>
[2017-11-28 09:54:46 +0100] Mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000008a6ef70>
[2017-11-28 09:54:46 +0100] Making base.
[2017-11-28 09:54:46 +0100] Cleaning directory: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:54:46 +0100] Removing : /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:54:46 +0100] Cloning into: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
[2017-11-28 09:54:47 +0100] Mounted https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000008a6ef70>
[2017-11-28 09:54:47 +0100] Processing target...https://github.com/tyranid/ZeroNights2017.git
[2017-11-28 09:54:47 +0100] Running tasks in stage: wait
[2017-11-28 09:54:47 +0100] Running tasks in stage: mount
[2017-11-28 09:54:47 +0100] Running tasks in stage: file
[2017-11-28 09:54:47 +0100] Running tasks in stage: code
[2017-11-28 09:54:47 +0100] code - CppChecker - #<Set:0x000000089fb408>
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="1.80"/>
    <errors>
    </errors>
</results>
[2017-11-28 09:54:47 +0100] Running tasks in stage: live
[2017-11-28 09:54:47 +0100] Running tasks in stage: done
[2017-11-28 09:54:47 +0100] Have 0 items pre ZAP filter.
[2017-11-28 09:54:47 +0100] Have 0 items post ZAP filter.
[2017-11-28 09:54:47 +0100] Generating report...[:to_s]
[2017-11-28 09:54:47 +0100] Running base reoprt...**

The sidekiq.log
# Logfile created on 2017-11-28 09:48:57 +0100 by logger.rb/53141
2017-11-28T08:49:02.337Z 8715 TID-aymls INFO: Running in ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
2017-11-28T08:49:02.337Z 8715 TID-aymls INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-11-28T08:49:02.337Z 8715 TID-aymls INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-11-28T08:49:02.337Z 8715 TID-aymls INFO: Booting Sidekiq 4.2.10 with redis options {:url=>nil}
2017-11-28T08:49:02.338Z 8715 TID-aymls INFO: Loading Schedule
2017-11-28T08:49:02.338Z 8715 TID-aymls INFO: Scheduling scanner_scheduler {"every"=>"1d", "class"=>"SchedulerScanner", "queue"=>"default"}
2017-11-28T08:49:02.339Z 8715 TID-aymls INFO: Schedules Loaded
2017-11-28T08:53:19.481Z 8715 TID-1hadao DynamicScanWorker JID-c16116ee5b1d7c6eff2ffc21 INFO: start
Loading scanner...
Mounting https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000007a3b108>
Cleaning directory: /home/vikas/line/tmp/github.com/tyranid/ZeroNights2017
Mounted https://github.com/tyranid/ZeroNights2017.git with #<Pipeline::GitMounter:0x00000007a3b108>
Processing target...https://github.com/tyranid/ZeroNights2017.git
Running tasks in stage: wait
Running tasks in stage: mount
Running tasks in stage: file
Running tasks in stage: code
code - CppChecker - #<Set:0x00000007c55c68>
undefined method `path' for nil:NilClass
Running tasks in stage: live
Running tasks in stage: done
Generating report...[:to_s]
Running base reoprt...
2017-11-28T08:53:20.977Z 8715 TID-1hadao DynamicScanWorker JID-c16116ee5b1d7c6eff2ffc21 INFO: fail: 1.496 sec
2017-11-28T08:53:20.978Z 8715 TID-1hadao WARN: {"context":"Job raised exception","job":{"class":"DynamicScanWorker","args":[1,1],"retry":2,"queue":"dynamic","backtrace":true,"jid":"c16116ee5b1d7c6eff2ffc21","created_at":1511859199.4787269,"enqueued_at":1511859199.4802892,"error_message":"no implicit conversion of nil into String","error_class":"TypeError","failed_at":1511859200.978007,"retry_count":0,"error_backtrace":["/home/vikas/Development/PCC_sysec/web/app/app/workers/dynamic_scan_worker.rb:71:in `exist?'","/home/vikas/Development/PCC_sysec/web/app/app/workers/dynamic_scan_worker.rb:71:in `perform'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/middleware.rb:10:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-retries-0.4.0/lib/sidekiq/retries/server/middleware.rb:15:in `call'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'","/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'"]},"jobstr":"{\"class\":\"DynamicScanWorker\",\"args\":[1,1],\"retry\":2,\"queue\":\"dynamic\",\"backtrace\":true,\"jid\":\"c16116ee5b1d7c6eff2ffc21\",\"created_at\":1511859199.4787269,\"enqueued_at\":1511859199.4802892}"}
2017-11-28T08:53:20.978Z 8715 TID-1hadao WARN: TypeError: no implicit conversion of nil into String
2017-11-28T08:53:20.978Z 8715 TID-1hadao WARN: /home/vikas/Development/PCC_sysec/web/app/app/workers/dynamic_scan_worker.rb:71:in `exist?'
/home/vikas/Development/PCC_sysec/web/app/app/workers/dynamic_scan_worker.rb:71:in `perform'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/middleware.rb:10:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-retries-0.4.0/lib/sidekiq/retries/server/middleware.rb:15:in `call'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/home/vikas/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'


I am really stuck here. Don't no whats causing the issue!!
