### ISSUE TITLE
Installation fails on Ubuntu 14 & 16

### ISSUE THREAD

**Issue by jackflax** [olacabs/jackhammer#84]
See below screen copy after running the install script -- please note that I launched two NEW different VM (Amazon EC2) running ubuntu 14 and ubuntu 16 ... same error ...

Step 16/48 : RUN npm install -g nsp
 ---> Running in d3526e2eaa3f
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-1052-aws
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nsp"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install -g nsp' returned a non-zero code: 1

Any advice???  Can you actually test your installation procedure and confirm its working?

Please tell me the exact hardware and operating system config you use and I will copy it to get this installed correctly.  

Thank you!

**Comment by jackflax** [comment]
Anyone? Is this project dead?

**Comment by kmadhusudhan** [comment]
let me know your docker version

**Comment by harie0x** [comment]
I am also getting the same issue in MAC OS X running docker version 17.03.1-ce. Log Copy below

Setting up node-node-uuid (1.4.0-1) ...
Setting up libc-ares-dev:amd64 (1.10.0-2ubuntu0.2) ...
Setting up node-abbrev (1.0.4-2) ...
Setting up node-ansi (0.2.1-1) ...
Setting up node-archy (0.0.2-1) ...
Setting up node-inherits (2.0.0-1) ...
Setting up node-block-stream (0.0.7-1) ...
Setting up node-delayed-stream (0.0.5-1) ...
Setting up node-combined-stream (0.0.4-1) ...
Setting up node-cookie-jar (0.3.1-1) ...
Setting up node-forever-agent (0.5.1-1) ...
Setting up node-mime (1.2.11-1) ...
Setting up node-form-data (0.1.0-1) ...
Setting up node-rimraf (2.2.2-2) ...
Setting up node-mkdirp (0.3.5-1) ...
Setting up node-graceful-fs (2.0.0-2) ...
Setting up node-fstream (0.1.24-1) ...
Setting up node-lru-cache (2.3.1-1) ...
Setting up node-sigmund (1.0.0-1) ...
Setting up node-minimatch (0.2.12-1) ...
Setting up node-fstream-ignore (0.0.6-2) ...
Setting up node-github-url-from-git (1.1.1-1) ...
Setting up node-glob (3.2.6-1) ...
Setting up nodejs-dev (0.10.25~dfsg2-2ubuntu1) ...
Setting up node-nopt (2.1.2-1) ...
Setting up node-npmlog (0.0.4-1) ...
Setting up node-osenv (0.0.3-1) ...
Setting up node-tunnel-agent (0.3.1-1) ...
Setting up node-json-stringify-safe (5.0.0-1) ...
Setting up node-qs (0.6.5-1) ...
Setting up node-request (2.26.1-1) ...
Setting up node-semver (2.1.0-2) ...
Setting up node-tar (0.1.18-1) ...
Setting up node-which (1.0.5-2) ...
Setting up node-gyp (0.10.10-2) ...
Setting up node-ini (1.1.0-1) ...
Setting up node-lockfile (0.4.1-1) ...
Setting up node-mute-stream (0.0.3-1) ...
Setting up node-normalize-package-data (0.2.2-1) ...
Setting up node-once (1.1.1-1) ...
Setting up node-read (1.0.4-1) ...
Setting up node-read-package-json (1.1.3-1) ...
Setting up node-retry (0.6.0-1) ...
Setting up node-sha (1.2.3-1) ...
Setting up node-slide (1.1.4-1) ...
Setting up nodejs-legacy (0.10.25~dfsg2-2ubuntu1) ...
Setting up npm (1.3.10~dfsg-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
 ---> fb705ac20e0e
Removing intermediate container 12d4d93b31cd
Step 16/48 : RUN npm install -g nsp
 ---> Running in 3fda109046e5
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.9.27-moby
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nsp"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install -g nsp' returned a non-zero code: 1

**Comment by raysabee** [comment]
I have tried everything, from setting the http version of the https://registry.npmjs.org/ as well as the "sudo npm_config_strict-ssl=false" but i have no luck.

Tried all the fixes i could find for the section below:

"
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm http GET https://registry.npmjs.org/nsp
npm ERR! Error: CERT_UNTRUSTED
"

I'm getting the exact same error as TS.

**Comment by kmadhusudhan** [comment]
Hi All,
i modified npm installation steps and created pull request . please do changes in your local web/Dockerfile and rebuild  the application . please let me know if you face same issue . 

Please refer pull request https://github.com/olacabs/jackhammer/pull/85

**Comment by raysabee** [comment]
Thanks for the quick reply!

I am getting the following error when replacing the content of the web/Dockerfile with the new verion:

Building web
ERROR: Dockerfile parse error line 27: unknown instruction: APT-GET

**Comment by kmadhusudhan** [comment]
modified docker  https://github.com/olacabs/jackhammer/pull/88

**Comment by raysabee** [comment]
Working much better and almost there.

On http://localhost:5000 it won't connect, i think because of:

Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer_redis_1 ... 
Starting jackhammer_redis_1 ... done
Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer_redis_1 ... done
Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer-db ... done
Starting jackhammer_redis_1 ... done
     _    _     ____  _  __ _   _     _     __  __  __  __  _____  ____    ___  ____    _   _  ____  
    | |  / \   / ___|| |/ /| | | |   / \   |  \/  ||  \/  || ____||  _ \  |_ _|/ ___|  | | | ||  _ \ 
 _  | | / _ \ | |    | ' / | |_| |  / _ \  | |\/| || |\/| ||  _|  | |_) |  | | \___ \  | | | || |_) |
| |_| |/ ___ \| |___ | . \ |  _  | / ___ \ | |  | || |  | || |___ |  _ <   | |  ___) | | |_| ||  __/ 
 \___//_/   \_\\____||_|\_\|_| |_|/_/   \_\|_|  |_||_|  |_||_____||_| \_\ |___||____/   \___/ |_|   



When running gem list i get:

gem list

*** LOCAL GEMS ***

addressable (2.5.2)
bigdecimal (1.2.8)
bundler (1.16.1)
did_you_mean (1.0.0)
ethon (0.11.0)
ffi (1.9.23)
io-console (0.4.5)
json (1.8.3)
metaclass (0.0.4)
mini_portile2 (2.3.0)
minitest (5.8.4)
mocha (1.5.0, 0.14.0)
net-telnet (0.1.1)
nokogiri (1.8.2)
power_assert (0.2.7)
psych (2.0.17)
public_suffix (3.0.2, 3.0.1)
rake (10.5.0)
rdoc (4.2.1)
ruby-progressbar (1.9.0)
terminal-table (1.8.0)
test-unit (3.1.7)
typhoeus (1.3.0)
unicode-display_width (1.3.0)
yajl-ruby (1.3.1)

**Comment by raysabee** [comment]
Just tried the fresh installation with a clean Linux Kali distro but having the same problems. Also edited the Dockerfile manually but i keep getting the same Mocha error as above.

**Comment by harie0x** [comment]
Myself tried the fresh installation in MAC OS X. I am also getting the Mocha gem Missing error as shown in the logs.

Status: Downloaded newer image for redis:latest
Creating jackhammer-db      ... done
Creating jackhammer_redis_1 ... done
Creating jackhammer_web_1   ... done
Starting jackhammer_redis_1 ... done
Starting jackhammer-db      ... done
Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer_redis_1 ... done
Starting jackhammer-db      ... done
Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer-db      ... done
Starting jackhammer_redis_1 ... done
Could not find gem 'mocha (~> 0.14.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
Starting jackhammer-db      ... done
Starting jackhammer_redis_1 ... done

**Comment by kmadhusudhan** [comment]
@harie0x 
We did not face this issue in our MAC OS X system . please add mocha gem in Gemfile and  rebuild the jackhamer . i tried same approach adding mocha in Gemfile, its installed . See below logs after adding mocha gem in Gemfile. And refer my Gemfile how it can be added , Gemfile content pasted below **cat Gemfile** command 

root@730c2d0057ab:/home/app# uname -a
Linux 730c2d0057ab 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@730c2d0057ab:/home/app# vi Gemfile
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies.....
Using rake 12.3.0
Using RedCloth 4.3.2
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using json 1.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 4.2.7.1
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using nokogiri 1.6.8.1
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.8
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.3
Using actionview 4.2.7.1
Using rack 1.6.8
Using rack-test 0.6.3
Using actionpack 4.2.7.1
Using globalid 0.4.1
Using activejob 4.2.7.1
Using mini_mime 1.0.0
Using mail 2.7.0
Using actionmailer 4.2.7.1
Using actionpack-action_caching 1.2.0
Using activemodel 4.2.7.1
Using arel 6.0.4
Using activerecord 4.2.7.1
Using multi_json 1.12.2
Using thor 0.19.4
Using railties 4.2.7.1
Using activerecord-session_store 1.1.0
Using addressable 2.3.6
Using aescrypt 1.0.0
Using arachni-reactor 0.1.0
Using arachni-rpc 0.2.1.2
Using awesome_print 1.2.0
Using bundler 1.16.1
Using ffi 1.9.18
Using childprocess 0.5.3
Using coderay 1.1.0
Using kramdown 1.4.1
Using msgpack 0.5.8
Using oj 2.12.14
Using oj_mimic_json 1.0.1
Using pony 1.8
Using rb-readline 0.5.1
Using rubyzip 1.1.6
Using terminal-table 1.4.5
Using ethon 0.11.0
Using typhoeus 0.6.9
Using selenium-webdriver 3.7.0
Using watir-webdriver 0.6.9
Using arachni 1.3.2
Using execjs 2.7.0
Using autoprefixer-rails 7.1.6
Using bcrypt 3.1.11
Using bcrypt-ruby 3.1.5
Using best_in_place 3.1.1
Using erubi 1.7.0
Using better_errors 2.4.0
Using debug_inspector 0.0.3
Using binding_of_caller 0.7.3
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.3
Using bootstrap-sass 3.3.7
Using momentjs-rails 2.17.1
Using bootstrap3-datetimepicker-rails 4.17.47
Using brakeman 4.0.1
Using uniform_notifier 1.10.0
Using bullet 5.6.1
Using bundler-audit 0.6.0
Using byebug 9.1.0
Using cancancan 2.1.1
Using xpath 2.1.0
Using capybara 2.16.0
Using chronic 0.10.2
Using numerizer 0.1.1
Using chronic_duration 0.10.6
Using climate_control 0.2.0
Using cocaine 0.5.8
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using coffee-rails 4.2.2
Using connection_pool 2.2.1
Using safe_yaml 1.0.4
Using crack 0.4.3
Using css_parser 1.6.0
Using curb 0.9.4
Using cvss 0.99.0
Using dm-core 1.2.1
Using dm-aggregates 1.2.0
Using dm-constraints 1.2.0
Using dm-migrations 1.2.0
Using fastercsv 1.5.5
Using json_pure 1.8.6
Using dm-serializer 1.2.2
Using dm-timestamps 1.2.0
Using dm-transactions 1.2.0
Using stringex 1.5.1
Using uuidtools 2.1.5
Using dm-types 1.2.2
Using dm-validations 1.2.0
Using data_mapper 1.2.0
Using data_objects 0.10.17
Using database_cleaner 1.6.2
Using dm-do-adapter 1.2.0
Using do_sqlite3 0.10.17
Using dm-sqlite-adapter 1.2.0
Using temple 0.8.0
Using tilt 2.0.8
Using haml 5.0.4
Using justify 1.0.2
Using logger-colors 1.0.0
Using ptools 1.3.5
Using sexp_processor 4.10.0
Using ruby_parser 3.10.1
Using sqlite3 1.3.13
Using sys-uname 1.0.3
Using dawnscanner 1.6.8
Using orm_adapter 0.5.0
Using responders 2.4.0
Using warden 1.2.7
Using devise 4.3.0
Using diff-lcs 1.3
Using docile 1.1.5
Using et-orbi 1.0.8
Using factory_girl 4.9.0
Using factory_girl_rails 4.9.0
Using faker 1.8.4
Using multipart-post 2.0.0
Using faraday 0.12.2
Using figaro 1.1.1
Using font-awesome-rails 4.7.0.2
Using foreman 0.84.0
Using multi_xml 0.6.0
Using httparty 0.15.6
Using gitlab 4.2.0
Using god 0.13.7
Using hashdiff 0.3.7
Using hashie 3.5.6
Using highline 1.7.8
Using htmlentities 4.3.4
Using httpclient 2.8.3
Using jbuilder 2.7.0
Using oauth 0.5.3
Using jira-ruby 1.4.3 from git://github.com/sumoheavy/jira-ruby.git (at master@6ac7a98)
Using logger-application 0.0.2
Using soap4r-ng 2.0.3
Using jira4r 1.3.0
Using jquery-rails 4.3.1
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using sass-rails 5.0.7
Using jquery-datatables-rails 3.4.0 from git://github.com/rweng/jquery-datatables-rails.git (at master@d486b31)
Using jquery-ui-rails 6.0.1
Using jquery-validation-rails 1.16.0
Using jsonpath 0.8.10
Using jwt 1.5.6
Using kgio 2.11.2
Using libv8 3.16.14.19 (x86_64-linux)
Using local_time 2.0.0
Using metaclass 0.0.4
Using method_source 0.9.0
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mimemagic 0.3.2
**Fetching mocha 0.14.0
Installing mocha 0.14.0**
Using mysql2 0.4.10
Using nested_form 0.3.2
Using oauth2 1.4.0
Using sawyer 0.8.1
Using octokit 4.7.0
Using omniauth 1.7.1
Using omniauth-oauth2 1.4.0
Using omniauth-github 1.3.0
Using redcarpet 3.4.0
Using owasp-pipeline 0.8.7
Using paperclip 5.0.0
Using premailer 1.11.1
Using premailer-rails 1.10.0
Using pry 0.11.3
Using pry-byebug 3.5.0
Using pry-rails 0.3.6
Using rack-protection 1.5.3
Using rails 4.2.7.1
Using rails-settings-cached 0.6.6
Using rails_autolink 1.1.6
Using raindrops 0.19.0
Using rdoc 4.3.0
Using redis 3.3.5
Using redis-store 1.4.1
Using redis-rack 2.0.3
Using redis-actionpack 5.0.2
Using redis-activesupport 5.0.4
Using redis-namespace 1.6.0
Using redis-rails 5.0.2
Using ref 2.0.0
Using remotipart 1.3.1
Using rolify 5.1.0
Using rprogram 0.3.2
Using rspec-support 3.7.0
Using rspec-core 3.7.0
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using rspec-rails 3.7.1
Using ruby-nmap 0.9.2
Using ruby-progressbar 1.9.0
Using rufus-scheduler 3.4.2
Using sdoc 0.4.2
Using sidekiq 4.2.10
Using sidekiq-limit_fetch 3.4.0
Using sidekiq-middleware 0.3.0
Using sidekiq-retries 0.4.0
Using sidekiq-scheduler 2.1.10
Using sidekiq-statistic 1.2.0
Using sidekiq-status 0.7.0
Using simplecov-html 0.10.2
Using simplecov 0.15.1
Using sinatra 1.4.8
Using spinjs-rails 1.4
Using spring 2.0.2
Using spring-commands-rspec 1.0.4
Using tag-it-rails 2.0.0
Using therubyracer 0.12.3
Using toastr-rails 1.0.3
Using turbolinks-source 5.0.3
Using turbolinks 5.0.1
Using uglifier 3.2.0
Using unicorn 5.4.0
Using web-console 2.3.0
Using webmock 3.1.1
Using whenever 0.10.0
Using will_paginate 3.1.6
Using will_paginate-bootstrap 1.0.1
Using yajl-ruby 1.3.1
Bundle complete! 91 Gemfile dependencies, 241 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# 
root@730c2d0057ab:/home/app# 
**root@730c2d0057ab:/home/app# cat Gemfile**
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'coffee-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
#jquery ui
gem 'jquery-ui-rails'
#authentication and roles
gem 'devise'
**gem 'mocha', '~> 0.14.0'**
gem 'cancancan'
gem 'rolify'
#bootstrap
gem 'bootstrap-sass'
# pagination
gem 'will_paginate'
gem 'will_paginate-bootstrap'
#validations
gem "jquery-validation-rails"
# scanning stuff
gem 'owasp-pipeline', '>= 0.8.7'
gem 'whenever'
gem 'chronic'
#github api
gem 'octokit'
#gitlab
gem 'gitlab'
#oauth
gem 'omniauth'
gem 'omniauth-github'
# redis && caching
gem 'redis-rails'
gem 'rails-settings-cached'
gem 'redis-namespace'
#sidekiq
gem 'sidekiq'
gem 'sidekiq-status'
gem 'sinatra', :require => false # for the UI
# ENV Variables
gem 'figaro'
#eager load notification
gem 'bullet'
#file upload
gem "paperclip", "~> 5.0.0"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
#file upload
gem 'remotipart', '~> 1.2'
#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# faker
gem 'faker'
#font awesome
gem "font-awesome-rails"
#nested from
gem "nested_form"
#jira integration
gem 'jira-ruby', github:'sumoheavy/jira-ruby'
gem 'soap4r-ng','2.0.3'
gem 'jira4r'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.42'
#gem 'puma','~> 2.12.3'
gem 'unicorn'
gem 'foreman'
gem 'actionpack-action_caching'
gem 'spinjs-rails'
gem 'activerecord-session_store'
gem 'crack'
gem 'execjs'
gem 'therubyracer'
gem 'ruby-nmap'
#wp scan
gem 'typhoeus'
gem 'addressable'
gem 'ruby-progressbar'
gem 'terminal-table'
gem 'yajl-ruby'
#string formation
gem 'kramdown'
gem 'rails_autolink'
gem 'RedCloth'
gem 'loofah'
gem 'premailer-rails'
gem 'arachni'
gem 'arachni-reactor'
gem 'sidekiq-scheduler'
gem 'toastr-rails'
gem 'local_time'
gem 'sidekiq-statistic'
gem 'sidekiq-middleware'
gem 'sidekiq-retries'
gem 'god'
#gem 'tagsinput-rails'
gem 'tag-it-rails'
gem 'best_in_place'
gem 'spring'
gem 'pry-rails'
gem 'pry-byebug'
gem 'aescrypt'
gem 'sidekiq-limit_fetch'
group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'
	gem 'rspec'
	gem "rspec-rails"
	gem "factory_girl_rails"
	gem 'capybara'
	gem 'spring-commands-rspec'
	gem 'database_cleaner'

end

group :development do
	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'
	gem 'better_errors'
	gem 'binding_of_caller'
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	#gem 'spring'
end
group :test do
	gem 'webmock', '>=1.17.2'
	gem 'simplecov'
end
root@730c2d0057ab:/home/app#

**Comment by harie0x** [comment]
Hi @KMadhuSudhan 

I am almost there. now, i am getting the rake aborted! error. I tried with the fresh installation in mac os x and modified the gem file to include mocha gem & docker file as per the pull request 88.


Removing intermediate container bd91ee02e488
 ---> 8f1645501cf5
Step 48/53 : ADD app/ /home/app
 ---> 1694eac6b5a8
Step 49/53 : RUN mkdir -p tmp
 ---> Running in beb4b10baf22
Removing intermediate container beb4b10baf22
 ---> 7b57e08c33e0
Step 50/53 : RUN mkdir -p tmp/pids
 ---> Running in a0acec41acc0
Removing intermediate container a0acec41acc0
 ---> 112cec24e36e
Step 51/53 : RUN mkdir -p log/scans
 ---> Running in 8d2150b923a3
Removing intermediate container 8d2150b923a3
 ---> 56f03b2c448d
Step 52/53 : WORKDIR /home/app
Removing intermediate container fd87e5dbac1d
 ---> 2f24b8b9f7eb
Step 53/53 : EXPOSE 3000
 ---> Running in c04cb52123b6
Removing intermediate container c04cb52123b6
 ---> e08fd6454f4f
Successfully built e08fd6454f4f
Successfully tagged jackhammer_web:latest
Creating network "jackhammer_default" with the default driver
Creating volume "jackhammer_mysql-data" with local driver
Pulling mysqldb (mysql:)...
latest: Pulling from library/mysql
f2aa67a397c4: Pull complete
1accf44cb7e0: Pull complete
2d830ea9fa68: Pull complete
740584693b89: Pull complete
4d620357ec48: Pull complete
ac3b7158d73d: Pull complete
a48d784ee503: Pull complete
f122eadb2640: Pull complete
3df40c552a96: Pull complete
da7d77a8ed28: Pull complete
f8aaeb9a4f41: Pull complete
5422e3698c48: Pull complete
Digest: sha256:04ff0d061fb05f5849415f644806584cd4a0a0baac07c8d9a8ad71fd629f845c
Status: Downloaded newer image for mysql:latest
Pulling redis (redis:)...
latest: Pulling from library/redis
b0568b191983: Pull complete
6637dc5b29fe: Pull complete
7b4314315f15: Pull complete
2fd86759b5ff: Pull complete
0f04862b5a3b: Pull complete
2db0056aa977: Pull complete
Digest: sha256:2a10443dced488731f0a3ed12e442c230d39b526f95ecb8e280cd1596705e822
Status: Downloaded newer image for redis:latest
Creating jackhammer_redis_1 ... done
Creating jackhammer-db      ... done
Creating jackhammer_web_1   ... done
Starting jackhammer_redis_1 ... done
Starting jackhammer-db      ... done

rake aborted!
LoadError: cannot load such file -- rails/all
/home/app/config/application.rb:2:in `require'
/home/app/config/application.rb:2:in `<top (required)>'
/home/app/Rakefile:4:in `require'
/home/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Starting jackhammer_redis_1 ... done
Starting jackhammer-db      ... done
rake aborted!
LoadError: cannot load such file -- rails/all
/home/app/config/application.rb:2:in `require'
/home/app/config/application.rb:2:in `<top (required)>'
/home/app/Rakefile:4:in `require'
/home/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Starting jackhammer-db      ... done
Starting jackhammer_redis_1 ... done
rake aborted!
LoadError: cannot load such file -- rails/all
/home/app/config/application.rb:2:in `require'
/home/app/config/application.rb:2:in `<top (required)>'
/home/app/Rakefile:4:in `require'
/home/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Starting jackhammer_redis_1 ... done
Starting jackhammer-db      ... done

**Comment by dkogue** [comment]
Hi all,
please did anyone manage to run Jackhammer successfully?  I am also getting the Mocha gem Missing error. Tried the solution here but it won't work. 
thanks
